version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dba
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - "27017:27017"
    networks:
      - ups_net
    volumes:
      - mongo_data:/data/db

networks:
  ups_net:
    driver: bridge

volumes:
  mongo_data:
    driver: local
